<?php
$quotes = [
    'Les serveurs se frisent les moustaches.',
    'Faut pas pousser mémé dans les orties.',
    'On avait un peu de gras sur France Loisirs, mais on va jongler.',
    'C’est à la fin de la foire qu’on compte les bouses.',
    'Je tente même pas le plan B, je passe au plan Z.',
    'De toute façon c’est pas la taille qui compte, c’est le coefficient de dilatation.',
    'Si vous avez le coeur sur la main, vous devez avoir les fesses à une drôle de place.',
    'Faut pas se mettre la rate au court-bouillon !',
    'Ce n’est pas aux vieux singes qu’on apprend à faire la grimace.',
    'C’est une orthodoxie à géométrie variable ce machin.',
    'On a en tout autour du bide des serveurs.',
    'C’est la foire d’empoigne !',
    'Ils savent faire de l’informatique comme moi je parle serbo-croate du nord.',
    'Faudrait pas qu’il se grignote tout seul la biscotte dans son coin.',
    'Airbrake marche pas, il a l’air brake.',
    'Ici, Dieu c’est moi.',
    'Je m’en tape le coquillard.',
    'C’est pas ceinture-bretelles, c’est ceinture-bretelles-parachute.',
    'C’est un sac de nouilles incroyable.',
    'On n’a pas le cul propre sur ce sujet.',
    'Ils avancent à la vitesse d’un escargot anémié.',
    'Le firewall t’envoie un paquet trop gros, et après, ça part en couille.',
    'C’est l’armée mexicaine leur boite.',
    'On s’enferme dans la cuisine, on met la traviata et on allume le gaz.',
    'Les devs chez TEA, ils font des trucs géniaux sur leurs blogs persos et les conneries, ils les font sur tea-ebook.com',
    'Avec mes petites mains potelées, je lui ai fait la danse du ventre.',
    'On a un MySQL bien branlé.',
    'Je suis désolé mon coco.',
    'C’est un truc un peu bite-couteau ça.',
    'Il est pas très joli, il est à notre image.',
    'Maintenant qu’on a une force de frappe, on se rend compte qu’on est à poil.',
    'Là on va ouvrir les entrailles d’un #ePub',
    'Plus on est près, moins on est loin.',
    'Vous faites des trucs d’ambitieux hein, pas des trucs de touche pipi.',
    'Tu seras béni sur sept générations.',
    'Il y a peut-être une paille au milieu.',
    'Ha ha ha ha, staging alive, staging alive…',
    'Dans /dev/null, personne ne vous entend crier.',
    'Il y en a qui vendent leur âme au diable, Pascal lui il vend sa RAM à MySQL.',
    'On les a un peu trop pris pour des Allemands.',
    'Je vous serai donc gré de suivre vos dossiers avant de faire des réponses à l’emporte pièce.',
    'Je suis venu, j’ai vu, et j’ai qu’un seul cul.',
    'S’il y en a un qui fait tilt, on prend la motte au cul.',
    'Quand je pense qu’on a touché le fond, ils creusent.',
    'Lui il est capable de grenouiller dans des instances d’actionnaires.',
    'Tu peux commencer à mourir, on va te soigner. Enfin, elle va te soigner.',
    'La machine de staging elle est un peu vitaminée mais bon pas tant que ça.',// En expliquant à Typhon sur quoi on fait tourner notre IC
    'Y a pas le début du commencement d’une cacahuète.',
    'Même les plus ayatollesques ont pas tiqué sur le truc, alors bon.',
    'Le boostrap c’est comme l’acronymse du LISP (List of Insipide and Stupid Parenthésis), sauf que c’est avec des div… LISD (List of Insipide and Stupid Div).'
];
