<?php
$quotes = [
    "Les serveurs se frisent la moustache",
    "Faut pas pousser mémé dans les orties",
    "On avait un peu de gras sur France Loisirs, mais on va jongler",
    "C'est à la fin de la foire qu'on compte les bouses",
    "Je tente même pas le plan B, je passe au plan Z",
    "De toute façon c'est pas la taille qui compte, c'est le coefficient de dilatation",
    "Si vous avez le coeur sur la main, vous devez avoir les fesses à une drôle de place",
    "Faut pas se mettre la rate au court-bouillon !",
    "Ce n'est pas aux vieux singes qu'on apprend à faire la grimace",
    "C'est une orthodoxie à géométrie variable ce machin.",
    "On a en tout autour du bide des serveurs.",
    "C'est la foire d'empoigne !",
    "Ils savent faire de l'informatique comme moi je parle serbo-croate du nord.",
    "Faudrait pas qu'il se gratte tout seul la biscotte dans son coin.",
    "Airbrake marche pas, il a l'air brake.",
    "Ici, Dieu c'est moi.",
    "Je men tappe le coquillard.",
];
